### ISSUE TITLE
Question: usage de I2C

### ISSUE THREAD

**Issue by Patriboom** [Barrois/Detecteur-ESP32-Cam#6]
Bonjour, 

je comprends que vous avez pu combiner la pise d'image par la caméra ESP32 - AI Thinker à des capteurs I2C.

Est-ce que la déviriation de la caméra fut nécessaire à cela ? 

Quelles broches utilisez-vous pour connecter les SDA et SCL des composants I2C ? 

Je n'avais jamais imaginé que les adresses des GPIO devaient référer aux broches de la puce principal, mais c'est plein de bon sens.

Merci de votre aide.

**Comment by Jodaille** [comment]
Bonjour,

à priori SDA et SCL ne sont accessibles que sur le connecteur de la caméra.

pour la dérivation via la nappe de la camera:
https://github.com/Barrois/Detecteur-ESP32-Cam-Blob-Detector/tree/main/documentation/FPC_24P_0.5mm_I2C_Derivation

Bernard pourra confirmer, les connexions caméra/i2c fonctionnent, il restait la partie initialisation/énumération de la caméra sur le bus. Il me semble que lorsque la caméra s'initialise au démarrage de la carte, le "sketch" prends en gros le premier périhpérique sur le bus I2C. De mémoire Bernard avait réussi à tricher avec un ordre particulier. @Barrois tu te souviens ?

**Comment by Barrois** [comment]
Salut Jody,Tu me pose une colle ***@***.*** tu te souviens ?" !!! Tu évoques un conflit sur I2C entre le la caméra et le PCA 9685 ?En relisant la dernière version  : https://github.com/Barrois/Detecteur-ESP32-Cam-Blob-Detector/blob/main/documentation/CaptureWithoutDelay_save3_7_RxTx_3_vetical_4/CaptureWithoutDelay_save3_7_RxTx_3_vetical_4.ino j'ai trouvé  le texte qui doit croorespondre à la résolution de ce problème : #include <Adafruit_PWMServoDriver.h>const int PIN_SDA = 1; // port 1 du esp32-cam sur le SDAconst int PIN_SCL = 3; // port 3 du esp32-cam sur le SCLconst int PAN_ID = 0; // Pan sur le port 0 du PCA9685const int TILT_ID = 1; // Tilt sur le port 1 du PCA9685Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();#define SERVOMIN 150 // this is the 'minimum' pulse length count (out of 4096)#define SERVOMAX 600 // this is the 'maximum' pulse length count (out of 4096)

**Comment by Patriboom** [comment]
Merci à vous deux, 

ce que j'y comprends, c'est que les broches 1 et 3 de la caméra monopolisent I2C, respectivement SDA et SCL.  C'est pourquoi vous avez dérivé la caméra vers une carte où il vous était possible de souder d'autres accès à ces broches du micro-contrôleur.
L'usage de la librairie PWMServoDriver.h est nul (car mis en commentaire), il est donc inutile de l'appeler.

const int PIN_SDA = 1;  // port 1 du esp32-cam sur le SDA
const int PIN_SCL = 3;  // port 3 du esp32-cam sur le SCL

Si c'est bien cela, j'étudierai le plan du ESP32-cam afin de m'y retrouver.

J'ai aussi lu, hier - mais je n'arrive pas à m'inscrire au forum (je ne reçois pas le message de confirmation) - qu'il serait plus simple encore d'y arriver.  Selon [Eurymedon](https://www.esp32.com/viewtopic.php?f=13&t=29342&p=101893&hilit=ai+thinker#p101893), 21 août dernier, il suffirait de fournir une horloge. 
Je tenterai de m'incrire au forum sous un autre nom afin d'y accéder enfin et vous reviendrai avec des détails.

Au plaisir et bon succès à vos études des frelons.

**Comment by Jodaille** [comment]
Bonjour,

oui en fait nous avons employé deux cartes de ce type: https://fr.aliexpress.com/item/4000099171451.html
pour avoir un connecteur de nappe côté caméra, et un autre avec une nappe "rallonge".
Les deux cartes sont soudées entre-elles.

Cela nous permettait d'avoir accès à SDA/SCL tout en conservant la caméra 
et la carte sD moyennant une autre bidouille. 
Si je me souviens bien: https://dr-mntn.net/2021/02/using-the-sd-card-in-1-bit-mode-on-the-esp32-cam-from-ai-thinker

Je pense avoir retrouvé un des sketchs concerné: https://github.com/Barrois/Detecteur-ESP32-Cam-Blob-Detector/blob/main/sketchbook/Esp32cam_FFT_Blob_PanTit_I2C_0/Esp32cam_FFT_Blob_PanTit_I2C_0.ino#L144-L148

Il me semble qu'il faut initialiser l'I2C avec Wire.begin(PIN_SDA, PIN_SCL); 
puis ensuite initialiser la caméra.
( Ou l'inverse, il y'a un loup :) )

Si jamais vous êtes d'accord Bernard serait ravi d'échanger avec vous,

Bonne journée.

**Comment by Patriboom** [comment]
Mais bien sûr, je serais ravi de d'échanger avec Bernard.
Je suis au Québec, cependant.  Il faut prévoir le décallage

Je vois dans [https://github.com/RuiSantosdotme/ESP32-CAM-eBook/blob/master/Code/Module_4/Video_Streaming_Web_Server_Sensor_Readings/](https://github.com/RuiSantosdotme/ESP32-CAM-eBook/blob/master/Code/Module_4/Video_Streaming_Web_Server_Sensor_Readings/Video_Streaming_Web_Server_Sensor_Readings.ino)
que le I2C_SCL est mis à la terre ( broche 15 du SCP32 [selon les specs de Espressif](https://docs.ai-thinker.com/_media/esp32/docs/esp32_cam_sch.pdf) avez-vous essayé cela ?

**Comment by Patriboom** [comment]
Selon [cet auteur](https://microdigisoft.com/esp32-interfacing-multiple-device-using-i2c-bus/), nous devrions pouvoir utiliser n'importe quelle paire de GPIO en guise de I2c SCL / SDA 

---------------  début de citation ----------------
_Use Any Pins as I2C with ESP32
We can configure almost any pin of ESP32 board with I2C capabilities using Wire.h library. To use pins with this library, you initialize the I2C using function as given below. So, we just need to set your desired SDA and SCL GPIOs on the I2C_SDA and I2C_SCL variables._

`Wire.begin(I2C_SDA, I2C_SCL);`

---------------  fin de citation ----------------

Je crois que c'est la commande qui manquait à ma programmation et qui m'a amené jusqu'à vous.
Je vous en donnerai des nouvelles.

**Comment by Patriboom** [comment]
Et oui, ça fonctionne!
J'ai repris le code de [Rui Santos](https://github.com/RuiSantosdotme/ESP32-CAM-eBook/tree/master/Code/Module_4/Video_Streaming_Web_Server_Sensor_Readings) avec de bons yeux et me suis rappelé avoir lu une consigne relative à l'usage de certaines broches de mise à terre.

Afin de faire fonctionner le tout:  il suffit de NE PAS utiliser la broche 16 (GND), celle immédiatement à côté de GPIO1 (U0TXD )
C'est là-dessus que j'ai perdu des heures!

Le code cité ci-haut semble bien fonctionnel.
Comme le dit la documentation, le signal WiFi de ESP32-CAM est faible  Il faut, par conséquent, garder le module près du routeur WiFi ou faire fonctionner avec une antenne externe.  Pour cela, il y a des consignes à suivre, il ne faut se contenter de connecter la première antenne venue.

Merci de votre attention et des recherches que vous avez faites suite à ma question.
Au plaisir.

**Comment by Barrois** [comment]
Salut Patriboom,
J'aimerai discuter un peu avec toi,
de ce que tu fais et pourquoi tu as besoin de ports supplémentaires sur l'Esp-Cam
bernard.barrois@orange.fr

**Comment by Patriboom** [comment]
Bonjour Bernard, 

	nous pouvons planifier un entretien audio-vidéo si vous le
désirez.


On Sat, 24 Sep 2022 00:47:16 -0700
Barrois ***@***.***> écrivites:

> Salut Patriboom,
> J'aimerai discuter un peu avec toi,
> de ce que tu fais et pourquoi tu as besoin de ports supplémentaires
> sur l'Esp-Cam ***@***.***
> 










---

Soyez artisans de paix.

Patrick Allaire, ptre

**Comment by Barrois** [comment]
Ok, 
Jody ça te va ?
 
Envoyé depuis l'application Mail Orange
----------------De : Patriboom ***@***.***>Envoyé : samedi 24 septembre 2022 18:33À : Barrois/Detecteur-ESP32-Cam-Blob-Detector ***@***.***>Cc : Barrois ***@***.***>; Mention ***@***.***>Objet : Re: [Barrois/Detecteur-ESP32-Cam-Blob-Detector] Question: usage de I2C (Issue #6)



Bonjour Bernard, 



 nous pouvons planifier un entretien audio-vidéo si vous le

désirez.





On Sat, 24 Sep 2022 00:47:16 -0700

Barrois ***@***.***> écrivites:



> Salut Patriboom,

> J'aimerai discuter un peu avec toi,

> de ce que tu fais et pourquoi tu as besoin de ports supplémentaires

> sur l'Esp-Cam ***@***.***

> 





















---



Soyez artisans de paix.



Patrick Allaire, ptre
